version: "3.2"
services:
  flask_service:
    image:  "flask_service"
    container_name:  flask_service
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/app
    links:
      - redis_service
    restart: always
  redis_service:
    image: "redis"
    container_name:  redis_service
    ports:
      - "6379:6379"
    restart: always